### ISSUE TITLE
Unable to find versions of some nuget packages

### ISSUE THREAD

**Issue by jarnawer** [mrcabellom/Yolo-MLScoring#1]
Hi!

Seems i can't compile solution in VS2017 (tried also on VS2015 with no luck). Nuget fails to find versions of these 3 packages:

Error		NuGet Package restore failed for project ObjectDetectionLib: Unable to find version '4.6.0-preview1-26524-04' of package 'System.Runtime.CompilerServices.Unsafe'.
  https://api.nuget.org/v3/index.json: Package 'System.Runtime.CompilerServices.Unsafe.4.6.0-preview1-26524-04' is not found on source 'https://api.nuget.org/v3/index.json'.
		
Error		NuGet Package restore failed for project ObjectDetectionLib: Unable to find version '4.6.0-preview1-26524-04' of package 'System.Memory'.
  https://api.nuget.org/v3/index.json: Package 'System.Memory.4.6.0-preview1-26524-04' is not found on source 'https://api.nuget.org/v3/index.json'.
			
Error		NuGet Package restore failed for project ObjectDetectionLib: Unable to find version '0.1.0-preview2-180526-1' of package 'System.Numerics.Tensors'.
  https://api.nuget.org/v3/index.json: Package 'System.Numerics.Tensors.0.1.0-preview2-180526-1' is not found on source 'https://api.nuget.org/v3/index.json'.

**Comment by mrcabellom** [comment]
Hi!, 

You must to add some news origin packages

- https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
- https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json
- https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

**Comment by jarnawer** [comment]
Just added those repositories and it now compiles succesfully, ;)

Thank you so much!
